language: python
python:
    - "2.7"
install:
    - git clone https://github.com/shaunduncan/helga ./helga
    - pip install -r helga/requirements.txt
    - pip install -e helga/
    - pip install -q -e . --use-mirrors
script:
    - python setup.py test
